/**
 * log-to-issues.ts
 *
 * Reads structured JSON error logs from Cloudflare Workers Logs API,
 * fingerprints them by (code, tool, normalized_message), deduplicates
 * against open GitHub issues (via a hidden marker), and creates or
 * updates issues with occurrence counts.
 *
 * Run: npx tsx scripts/log-to-issues.ts
 */

const CF_API = "https://api.cloudflare.com/client/v4";
const GH_API = "https://api.github.com";

const {
  CLOUDFLARE_API_TOKEN = "",
  CLOUDFLARE_ACCOUNT_ID = "",
  CLOUDFLARE_WORKER_NAME = "translation-helps-mcp",
  GITHUB_TOKEN = "",
  GITHUB_REPO = "",
  LOOKBACK_HOURS = "1",
} = process.env;

interface WorkerLogEntry {
  level?: string;
  code?: string;
  tool?: string;
  message?: string;
  ts?: string;
}

interface GitHubIssue {
  number: number;
  title: string;
  body: string;
  state: string;
  labels: Array<{ name: string }>;
}

const ISSUE_LABEL = "auto:error-log";
const MARKER_PREFIX = "<!-- auto-error-fingerprint:";

function fingerprint(entry: WorkerLogEntry): string {
  const code = entry.code ?? "UNKNOWN";
  const tool = entry.tool ?? "unknown";
  // Normalize the message: strip UUIDs, numbers, file paths for dedup
  const msg = (entry.message ?? "")
    .replace(/[0-9a-f-]{36}/gi, "<uuid>")
    .replace(/\b\d+\b/g, "<n>")
    .slice(0, 200);
  return `${code}::${tool}::${msg}`;
}

async function fetchWorkerLogs(): Promise<WorkerLogEntry[]> {
  if (!CLOUDFLARE_API_TOKEN || !CLOUDFLARE_ACCOUNT_ID) {
    console.error("Missing CLOUDFLARE_API_TOKEN or CLOUDFLARE_ACCOUNT_ID");
    process.exit(0);
  }

  const since = new Date(
    Date.now() - parseInt(LOOKBACK_HOURS) * 3600 * 1000,
  ).toISOString();
  const url = `${CF_API}/accounts/${CLOUDFLARE_ACCOUNT_ID}/workers/scripts/${CLOUDFLARE_WORKER_NAME}/logs?since=${since}&level=error`;

  const response = await fetch(url, {
    headers: { Authorization: `Bearer ${CLOUDFLARE_API_TOKEN}` },
  });

  if (!response.ok) {
    console.error(
      `Workers Logs API error: ${response.status} — ${await response.text()}`,
    );
    return [];
  }

  const data = (await response.json()) as {
    result?: Array<{ logs?: WorkerLogEntry[] }>;
  };
  const entries: WorkerLogEntry[] = [];
  for (const item of data.result ?? []) {
    for (const log of item.logs ?? []) {
      if (log.level === "error") entries.push(log);
    }
  }

  console.log(`Found ${entries.length} error log entries.`);
  return entries;
}

async function fetchOpenIssues(): Promise<GitHubIssue[]> {
  const [owner, repo] = (GITHUB_REPO || "owner/repo").split("/");
  const url = `${GH_API}/repos/${owner}/${repo}/issues?state=open&labels=${ISSUE_LABEL}&per_page=100`;
  const response = await fetch(url, {
    headers: {
      Authorization: `Bearer ${GITHUB_TOKEN}`,
      Accept: "application/vnd.github+json",
    },
  });
  if (!response.ok) return [];
  return response.json() as Promise<GitHubIssue[]>;
}

async function createOrUpdateIssue(
  fp: string,
  count: number,
  sample: WorkerLogEntry,
  existingIssue?: GitHubIssue,
): Promise<void> {
  const [owner, repo] = (GITHUB_REPO || "owner/repo").split("/");
  const marker = `${MARKER_PREFIX}${fp} -->`;
  const title = `[${sample.code ?? "ERROR"}] ${sample.tool ?? "unknown"}: ${(sample.message ?? "").slice(0, 60)}`;
  const body =
    `${marker}\n\n` +
    `**Error Code:** \`${sample.code ?? "UNKNOWN"}\`\n` +
    `**Tool:** \`${sample.tool ?? "unknown"}\`\n` +
    `**Occurrences (last ${LOOKBACK_HOURS}h):** ${count}\n\n` +
    `**Sample log entry:**\n\`\`\`json\n${JSON.stringify(sample, null, 2)}\n\`\`\`\n\n` +
    `*Auto-generated by [error-issues workflow](/.github/workflows/error-issues.yml)*`;

  if (existingIssue) {
    // Add a comment with updated count
    const commentUrl = `${GH_API}/repos/${owner}/${repo}/issues/${existingIssue.number}/comments`;
    await fetch(commentUrl, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${GITHUB_TOKEN}`,
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        body: `**Recurrence:** ${count} occurrences in the last ${LOOKBACK_HOURS}h.\n\nSample:\n\`\`\`json\n${JSON.stringify(sample, null, 2)}\n\`\`\``,
      }),
    });
    console.log(`Updated issue #${existingIssue.number}: ${title}`);
  } else {
    // Create new issue
    const issueUrl = `${GH_API}/repos/${owner}/${repo}/issues`;
    await fetch(issueUrl, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${GITHUB_TOKEN}`,
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ title, body, labels: [ISSUE_LABEL] }),
    });
    console.log(`Created issue: ${title}`);
  }
}

async function main(): Promise<void> {
  const logs = await fetchWorkerLogs();
  if (logs.length === 0) {
    console.log("No error logs found. Nothing to do.");
    return;
  }

  const openIssues = await fetchOpenIssues();

  // Group by fingerprint
  const groups = new Map<string, { count: number; sample: WorkerLogEntry }>();
  for (const entry of logs) {
    const fp = fingerprint(entry);
    const existing = groups.get(fp);
    if (existing) {
      existing.count++;
    } else {
      groups.set(fp, { count: 1, sample: entry });
    }
  }

  // Build fingerprint → issue map
  const issueMap = new Map<string, GitHubIssue>();
  for (const issue of openIssues) {
    const match = issue.body?.match(/<!-- auto-error-fingerprint:(.*?) -->/);
    if (match) issueMap.set(match[1].trim(), issue);
  }

  // Create or update issues
  for (const [fp, { count, sample }] of groups) {
    await createOrUpdateIssue(fp, count, sample, issueMap.get(fp));
  }

  console.log(`Done. Processed ${groups.size} unique error fingerprints.`);
}

main().catch((err) => {
  console.error("log-to-issues failed:", err);
  process.exit(1);
});
