/**
 * Cloudflare Worker entry point — translation-helps-mcp v2.
 *
 * Side-by-side with Pages v1: the app is mounted under BASE_PATH (/v2) so the
 * existing production site at the domain root is never replaced.
 *
 * Routing (BASE_PATH = /v2):
 *   /v2/mcp[/]*  → TranslationHelpsMCP McpAgent (Durable Object)
 *   /v2/api/tool → direct tool runner (Skills chat layer)
 *   /v2/*        → SvelteKit website (Workers Assets)
 *   /mcp[/]*     → alias of /v2/mcp (workers.dev convenience)
 *   /            → redirect → /v2/
 */

import { TranslationHelpsMCP } from "./mcp/agent.js";
import { logger } from "./core/logger.js";
import { normalizeToolArgs } from "./mcp/normalizeToolArgs.js";
import { TOOL_REGISTRY } from "./mcp/toolRegistry.js";
import { ApiClientError } from "./mcp/apiClient.js";
import { buildMcpManifest } from "./mcp/manifest.js";
// Generated by @sveltejs/adapter-cloudflare — handles SSR + /v2/api/* routes.
// Built before `wrangler deploy` via `cd web && npm run build`.
import svelteKit from "../web/.svelte-kit/cloudflare/_worker.js";

/** Public mount path for the v2 app. Must match SvelteKit kit.paths.base.
 * NOTE: must NOT be exported — workerd requires every top-level export of the
 * entry module to be a handler/DO class, and a string export crashes startup. */
const BASE_PATH = "/v2";

const mcpHandlerV2 = TranslationHelpsMCP.serve(`${BASE_PATH}/mcp`, {
  binding: "MCP_AGENT",
});
const mcpHandlerRoot = TranslationHelpsMCP.serve("/mcp", {
  binding: "MCP_AGENT",
});

export { TranslationHelpsMCP };

export interface Env {
  MCP_AGENT: DurableObjectNamespace;
  TRANSLATION_HELPS_CACHE: KVNamespace;
  ZIP_FILES: R2Bucket;
  ANALYTICS: AnalyticsEngineDataset;
  API?: Fetcher;
  API_BASE_URL?: string;
  TOOL_SECRET?: string;
  OPENAI_API_KEY?: string;
  ASSETS: Fetcher;
  BASE_PATH?: string;
}

export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const url = new URL(request.url);
    const base = (env.BASE_PATH || BASE_PATH).replace(/\/$/, "") || "/v2";

    if (url.pathname === "/" || url.pathname === "") {
      return Response.redirect(new URL(`${base}/`, url).toString(), 302);
    }

    if (url.pathname === "/mcp" || url.pathname.startsWith("/mcp/")) {
      return mcpHandlerRoot.fetch(request, env, ctx);
    }
    if (
      url.pathname === `${base}/mcp` ||
      url.pathname.startsWith(`${base}/mcp/`)
    ) {
      return mcpHandlerV2.fetch(request, env, ctx);
    }

    if (
      (url.pathname === `${base}/api/tool` || url.pathname === "/api/tool") &&
      request.method === "POST"
    ) {
      return handleToolCall(request, env);
    }

    if (
      (url.pathname === `${base}/api/mcp-manifest` ||
        url.pathname === "/api/mcp-manifest") &&
      request.method === "GET"
    ) {
      return new Response(
        JSON.stringify(buildMcpManifest({ mcpEndpoint: `${base}/mcp` })),
        {
          status: 200,
          headers: {
            "Content-Type": "application/json",
            "Access-Control-Allow-Origin": "*",
          },
        },
      );
    }

    // SvelteKit SSR + static assets under /v2
    return svelteKit.fetch(request, env, ctx);
  },
};

async function handleToolCall(request: Request, env: Env): Promise<Response> {
  const cors = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, X-Tool-Secret",
  };

  if (request.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: cors });
  }

  if (env.TOOL_SECRET) {
    const provided = request.headers.get("X-Tool-Secret");
    if (provided !== env.TOOL_SECRET) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { "Content-Type": "application/json", ...cors },
      });
    }
  }

  let body: {
    name?: string;
    params?: Record<string, unknown>;
    requestId?: string;
  };
  try {
    body = await request.json();
  } catch {
    return new Response(JSON.stringify({ error: "Invalid JSON body" }), {
      status: 400,
      headers: { "Content-Type": "application/json", ...cors },
    });
  }

  const { name, params = {}, requestId = crypto.randomUUID() } = body;
  if (!name) {
    return new Response(JSON.stringify({ error: "Missing tool name" }), {
      status: 400,
      headers: { "Content-Type": "application/json", ...cors },
    });
  }

  const tool = TOOL_REGISTRY[name];
  if (!tool) {
    return new Response(JSON.stringify({ error: `Unknown tool: "${name}"` }), {
      status: 404,
      headers: { "Content-Type": "application/json", ...cors },
    });
  }

  try {
    const normalized = normalizeToolArgs(name, params);
    const validated = tool.inputSchema.parse(normalized);
    const result = await tool.handler(validated, env, requestId);

    return new Response(
      JSON.stringify({
        structuredContent: result.structuredContent,
        content: result.content,
      }),
      { status: 200, headers: { "Content-Type": "application/json", ...cors } },
    );
  } catch (err) {
    if (err instanceof ApiClientError && err.status === 404) {
      const notAvail = {
        available: false,
        code: "RESOURCE_NOT_AVAILABLE",
        message: err.message,
      };
      return new Response(
        JSON.stringify({
          structuredContent: notAvail,
          content: [{ type: "text", text: JSON.stringify(notAvail) }],
        }),
        {
          status: 200,
          headers: { "Content-Type": "application/json", ...cors },
        },
      );
    }
    const message = err instanceof Error ? err.message : String(err);
    logger.error("tool:error", { name, message });
    return new Response(JSON.stringify({ error: message }), {
      status: 400,
      headers: { "Content-Type": "application/json", ...cors },
    });
  }
}
